server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/}
  forward-headers-strategy: framework

app:
  secret: ${APP_SECRET:dev-secret-key-should-be-changed}
  jwt:
    token:
      expires-in: ${APP_JWT_TOKEN_EXPIRES_IN:3600000} # 60 minutes in milliseconds
    refresh-token:
      expires-in: ${APP_JWT_REFRESH_TOKEN_EXPIRES_IN:86400000} # 24 hours in milliseconds
    remember-me:
      expires-in: ${APP_JWT_REMEMBER_ME_EXPIRES_IN:1728000000} # 20 days in milliseconds
  registration:
    email:
      token:
        expires-in: ${APP_REGISTRATION_EMAIL_TOKEN_EXPIRES_IN:3600000} # 60 minutes in milliseconds
    password:
      token:
        expires-in: ${APP_REGISTRATION_PASSWORD_TOKEN_EXPIRES_IN:3600000} # 60 minutes in milliseconds
  default-locale: ${APP_DEFAULT_LOCALE:en}
  default-timezone: ${APP_DEFAULT_TIMEZONE:Europe/Istanbul}
  url: ${APP_URL:http://localhost:8080}
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}

spring:
  application:
    name: ${APP_NAME:UniCircle}
    description: ${APP_DESCRIPTION:University Of Seoul Circle Application}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:none}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/unicircle
    username: universe
    password: universe
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:50MB}
  messages:
    basename: locales.messages
    encoding: UTF-8
    cache-duration: ${MESSAGES_CACHE_DURATION:-1}
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:ABC@coolcool.com}
    password: ${MAIL_PASSWORD:fhdf grua mqhs jmni}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          ssl:
            enable: ${MAIL_SSL:false}
          tls:
            enable: ${MAIL_TLS:false}

  docker:
    compose:
      lifecycle-management: none

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    operationsSorter: alpha
    tagsSorter: alpha
    path: ${SWAGGER_PATH:/swagger-ui}
  show-actuator: true